version: '3.7'
services:

  cloaki:
    build:
      context: . 
      dockerfile: ./Dockerfile
    container_name: cloaki
    restart: unless-stopped
    ports: 
      - 8080:8080
    volumes:
      - /tmp/cloaki:/cloaki